flags: {}
extra-package-dbs: []
packages:
- '.'
- location:
    git: git@github.com:agrafix/elm-bridge
    commit: 76acecc7ac90d5251229efd6671756854b34ebf2
extra-deps:
- aeson-0.11.1.0
- base-orphans-0.5.3
- conduit-extra-1.1.11
- cpphs-1.20.1
- engine-io-1.2.13
- fail-4.9.0.0
- socket-io-1.3.5
- text-1.2.2.0
- wai-extra-3.0.14.1
- yaml-0.8.15.3
- users-0.5.0.0
- users-postgresql-simple-0.5.0.2
resolver: lts-5.1
